# For copyright and license terms, see COPYRIGHT.rst (top level of repository)
# Repository: https://github.com/C3S/collecting_society
from trytond.pool import Pool
from .account import *
from .account_invoice import *
from .bank import *
from .collecting_society import *
from .configuration import *
from .party import *
from .web_user import *


def register():
    Pool.register(
        BankAccount,
        BankAccountNumber,
        AccessControlEntry,
        AccessPermission,
        AccessRole,
        AccessRolePermission,
        AccessControlEntryRole,
        CollectingSociety,
        Artist,
        ArtistArtist,
        ArtistPayeeAcceptance,
        ArtistIdentifierSpace,
        ArtistIdentifier,
        AccountMove,
        AllocationAccountInvoice,
        Invoice,
        InvoiceLine,
        UserRole,
        User,
        UserResUser,
        UserUserRole,
        UserParty,
        License,
        Creation,
        CreationDerivative,
        CreationRole,
        CreationIdentifierSpace,
        CreationIdentifier,
        CreationRight,
        CreationRightCreationRight,
        ArtistPlaylist,
        ArtistPlaylistItem,
        TariffCategory,
        TariffRelevanceCategory,
        TariffCategoryTariffRelevanceCategory,
        TariffRelevance,
        EventIndicators,
        LocationIndicators,
        LocationIndicatorsPeriod,
        LocationSpaceIndicators,
        WebsiteResourceIndicators,
        ReleaseIndicators,
        UtilisationIndicators,
        TariffSystem,
        TariffAdjustmentCategory,
        TariffCategoryTariffAdjustmentCategory,
        TariffAdjustment,
        Tariff,
        CreationTariffCategory,
        Checksum,
        Storehouse,
        HarddiskLabel,
        Harddisk,
        FilesystemLabel,
        Filesystem,
        HarddiskTest,
        Content,
        Fingerprintlog,
        Label,
        Publisher,
        Release,
        ReleaseTrack,
        ReleaseIdentifierSpace,
        ReleaseIdentifier,
        ReleaseRight,
        ReleaseRightReleaseRight,
        ArtistRelease,
        Instrument,
        CreationRightInstrument,
        Genre,
        ReleaseGenre,
        Style,
        ReleaseStyle,
        LocationSpaceCategory,
        LocationCategory,
        Location,
        LocationSpace,
        Event,
        EventPerformance,
        WebsiteCategory,
        WebsiteResourceCategory,
        WebsiteCategoryWebsiteResourceCategory,
        Website,
        WebsiteResource,
        WebsiteResourceCreation,
        Device,
        DeviceAssignment,
        UtilisationCreationlist,
        UtilisationCreationlistItem,
        DeviceMessageFingerprintCreationlist,
        DeviceMessageFingerprintCreationlistItem,
        DeviceMessage,
        DeviceMessageDeviceMessage,
        DeviceMessageFingerprint,
        DeviceMessageFingerprintMatchStart,
        DeviceMessageFingerprintMergeStart,
        DeviceMessageFingerprintMergeSelect,
        DeviceMessageUsagereport,
        Distribution,
        DistributionAccountMove,
        DistributionPlan,
        Collection,
        Allocation,
        CollectStart,
        DeclarationGroup,
        Declaration,
        Utilisation,
        DistributeStart,
        Configuration,
        PartyIdentifierSpace,
        PartyIdentifier,
        Party,
        PartyCategory,
        ContactMechanism,
        Category,
        Address,
        module='collecting_society', type_='model')
    Pool.register(
        Collect,
        Distribute,
        DeviceMessageFingerprintMatch,
        DeviceMessageFingerprintMerge,
        AllocationInvoice,
        UtilisationCalculate,
        UtilisationConfirm,
        UtilisationFinalize,
        module='collecting_society', type_='wizard')
